name: Postlister Bronze Kristiansand Tilsyn

on:
  push:
    branches: [ "master" ]
    paths:
      - "bronze/postlister/opengov/kristiansand/running_daily/tilsyn/setup.py"
  workflow_dispatch:

jobs:
  build-and-upload-wheel:
    uses: ./.github/workflows/build_upload_wheel.yml
    with:
      package_dir: "bronze/postlister/opengov/kristiansand/running_daily/tilsyn"
      package_name: "kristiansand-tilsyn"
      python_version: "3.11"
      blob_prefix: "postlister/bronze/wheels"
    secrets: inherit
